import type { Locale, PersonaSlug } from "./content";
type Campaign = {
  title: string; accent: string; intro: string; problemTitle: string; problem: string;
  fact: string; factTitle: string; factBody: string; source: string;
  steps: [string, string][]; question: string; answer: string; offer: string;
};
export const campaigns: Record<Locale, Record<PersonaSlug, Campaign>> = {
  fr: {
    "early-signs": {
      title: "Vos pieds changent.", accent: "Votre attention aussi.",
      intro: "Un gros orteil qui se rapproche du deuxième. Une chaussure qui frotte. Comprendre ces premiers signes, c’est déjà faire une place à vos pieds dans votre quotidien. Découvrez l’approche musculaire Albea.",
      problemTitle: "Une petite gêne mérite une vraie réponse.",
      problem: "Vous n’avez pas besoin d’attendre que votre routine devienne inconfortable pour vous informer. Commencez par observer ce qui change, les chaussures qui gênent et les moments où vos pieds vous sollicitent. Un professionnel pourra vous aider à comprendre la situation.",
      fact: "Parfois indolore", factTitle: "Un hallux valgus peut commencer sans douleur.", factBody: "L’absence de douleur ne suffit donc pas à savoir si l’alignement du gros orteil évolue.", source: "basics",
      steps: [["Observer sans s’alarmer", "Repérez les frottements et les changements de forme. Notez vos questions pour votre prochaine consultation."], ["Revoir le chaussage", "Un avant-pied large et souple laisse plus de place au gros orteil. Évitez les coutures sur la zone sensible."], ["Comprendre vos options", "Distinguez les gestes de confort, les traitements et les approches encore en développement, comme Albea."]],
      question: "Puis-je empêcher un hallux valgus d’apparaître ?", answer: "Aucune garantie individuelle n’est possible. Le chaussage est un facteur sur lequel agir, mais l’hérédité et la forme du pied comptent aussi. Albea n’a pas démontré d’effet préventif.",
      offer: "Une nouvelle place pour vos pieds, dans votre quotidien.",
    },
    "family-history": {
      title: "Une histoire de famille.", accent: "Des choix qui vous appartiennent.",
      intro: "Quand un parent a un hallux valgus, on regarde parfois ses propres pieds autrement. Transformez cette question en une routine informée, avec des repères concrets et une nouvelle approche à découvrir.",
      problemTitle: "Anticiper commence par comprendre.",
      problem: "L’expérience d’un proche peut donner envie de prendre les devants. Elle ne vous dit pas quel sera votre parcours. Plutôt que de rechercher une promesse absolue, faites le point sur votre confort, votre chaussage et ce que vous souhaitez demander à un professionnel.",
      fact: "L’hérédité compte", factTitle: "Le risque ne se résume pas aux chaussures.", factBody: "Une prédisposition familiale fait partie des facteurs favorisants décrits par l’Assurance Maladie.", source: "basics",
      steps: [["Connaître votre histoire", "Parlez des antécédents familiaux lors d’un bilan si cette question vous préoccupe."], ["Choisir de l’espace", "Des chaussures adaptées à la largeur de l’avant-pied constituent un point de départ concret."], ["Suivre les preuves", "Intéressez-vous aux résultats d’études et à leurs limites avant d’adopter une nouvelle technologie."]],
      question: "Albea peut-il modifier mon risque familial ?", answer: "Cela n’a pas été démontré. Le concept explore une activation musculaire ciblée ; il ne permet pas de promettre que l’histoire familiale ne se répétera pas.",
      offer: "Faites une place à une approche réfléchie.",
    },
    "active-living": {
      title: "Vous aimez bouger.", accent: "Pensez aussi à vos pieds.",
      intro: "Marche, sorties, week-ends dehors : vos pieds accompagnent tout ce que vous aimez. Entre deux activités, découvrez Albea, un concept de soin musculaire pensé pour un moment au calme.",
      problemTitle: "Le prochain kilomètre commence aussi au repos.",
      problem: "Quand une chaussure frotte ou qu’un gros orteil devient sensible, cela peut changer le plaisir d’une sortie. Prendre le temps de comprendre cette gêne est plus utile que de simplement la masquer. Votre routine peut commencer par quelques observations et un chaussage mieux adapté.",
      fact: "Chaque pas", factTitle: "L’articulation du gros orteil participe à la marche.", factBody: "Un hallux valgus peut entraîner des douleurs à la marche et des difficultés de chaussage.", source: "basics",
      steps: [["Vérifier vos chaussures", "Gardez suffisamment de place à l’avant-pied et repérez les zones de frottement après vos sorties."], ["Écouter une gêne persistante", "Une douleur qui modifie votre marche mérite un avis, plutôt qu’une nouvelle promesse de performance."], ["Créer un temps calme", "Albea est imaginé pour une utilisation au repos. Sa durée d’utilisation et ses réglages restent à valider."]],
      question: "Albea améliore-t-il la récupération ou les performances ?", answer: "Ces bénéfices ne sont pas établis. Albea n’est pas présenté comme un dispositif à utiliser pendant le sport. Les bénéfices, la sécurité et le protocole doivent être étudiés.",
      offer: "Un petit rituel, entre vos grandes envies.",
    },
    "on-your-feet": {
      title: "Toute la journée debout.", accent: "Un moment pour vous.",
      intro: "Soins, commerce, restauration : vos journées demandent beaucoup à vos pieds. Vous recherchez moins de fatigue et plus de confort ? Commençons par ce que dit la recherche, puis découvrez le concept Albea.",
      problemTitle: "La fatigue n’est pas un manque de volonté.",
      problem: "Une longue journée debout peut peser sur le corps, surtout lorsque la posture varie peu. La réponse concerne aussi l’organisation du travail et les possibilités de pause. Albea explore, de son côté, une routine musculaire au repos à la maison.",
      fact: "Plus de 5 millions", factTitle: "de salariés debout ou piétinant au moins 20 h par semaine.", factBody: "Donnée SUMER 2017 rapportée par l’INRS en 2021. La station debout prolongée est associée à la fatigue et à l’inconfort.", source: "standing",
      steps: [["Varier les positions", "Discutez des possibilités de mouvement et d’alternance assis-debout avec votre employeur ou la santé au travail."], ["Revoir l’environnement", "Chaussures, sol et organisation méritent d’être évalués ensemble. Une solution anti-fatigue ne suffit pas à elle seule."], ["Garder un moment pour soi", "Le concept Albea s’inscrit dans un temps de repos, avec quatre électrodes intégrées dans un support ouvert."]],
      question: "Albea permet-il de rester debout plus longtemps ?", answer: "Ce n’est pas un bénéfice démontré. Les recherches sur le travail debout ne valident pas Albea. Le produit ne remplace ni les pauses, ni l’adaptation du poste, ni un avis en santé au travail.",
      offer: "Après avoir pris soin de tout. Pensez à vous.",
    },
    "lifelong-movement": {
      title: "Vos promenades.", accent: "Vos habitudes. Votre liberté.",
      intro: "Continuer à profiter du marché, d’une visite ou d’une balade : le confort des pieds compte dans les petites libertés du quotidien. Découvrez des repères utiles et le concept Albea.",
      problemTitle: "Prendre soin de ce qui vous porte.",
      problem: "Avec les années, une chaussure qui serre ou une gêne sous le pied peut prendre davantage de place dans la journée. Une routine simple commence par regarder ses pieds et parler des difficultés rencontrées, sans considérer la douleur comme inévitable.",
      fact: "≈ 30 %", factTitle: "de la population âgée serait concernée par l’hallux valgus.", factBody: "Estimation rapportée par l’Assurance Maladie. Votre situation mérite une appréciation individuelle.", source: "basics",
      steps: [["Regarder régulièrement", "Prenez le temps d’observer la peau, les zones de frottement et les changements de confort."], ["Choisir un bon maintien", "Privilégiez une chaussure adaptée, assez large et qui maintient le talon."], ["En parler tôt", "Une gêne pour marcher mérite un avis professionnel. La simplicité d’un objet ne suffit pas à établir qu’il vous convient."]],
      question: "Albea convient-il à toutes les personnes âgées ?", answer: "La population d’utilisation et les contre-indications restent à établir. Une situation personnelle, notamment un diabète ou des problèmes de sensibilité, nécessite un avis adapté. Le concept ne promet pas de prévenir les chutes.",
      offer: "De l’attention pour les pas qui comptent.",
    },
  },
  en: {
    "early-signs": {
      title: "Small changes in your feet.", accent: "A reason to pay attention.",
      intro: "A big toe drifting inward. A shoe that rubs. Understanding the first changes is a practical place to start. Meet Albea Pulse, a new muscle-focused foot-care concept.",
      problemTitle: "A little discomfort deserves a thoughtful response.",
      problem: "You can start learning before your daily routine becomes uncomfortable. Notice what changes, which shoes cause pressure and what you want to ask a professional. An individual assessment can help you understand the options.",
      fact: "Slowly, over time", factTitle: "Bunions often develop gradually.", factBody: "The bones around the big-toe joint move out of alignment. Pressure and irritation can then affect comfort.", source: "basics",
      steps: [["Notice the changes", "Keep track of rubbing, toe shape and questions you want to raise at an appointment."], ["Make more room", "Check the width of the toe box. A shoe should accommodate your foot without squeezing it."], ["Understand the options", "Separate comfort measures and established treatment from approaches still being developed, including Albea."]],
      question: "Can I stop a bunion from developing?", answer: "There is no individual guarantee. Footwear is one factor you can address, but inherited structure also matters. Albea has not demonstrated prevention of bunions.",
      offer: "Make room for a new kind of foot-care routine.",
    },
    "family-history": {
      title: "A family history.", accent: "Your own next step.",
      intro: "When a parent has bunions, you may start looking at your own feet differently. Turn that question into informed choices, practical habits and a new approach to explore.",
      problemTitle: "Thinking ahead starts with understanding.",
      problem: "A relative’s experience can make you want to take action. It cannot tell you exactly what will happen to you. Focus on your comfort, your footwear and the questions you would like to discuss with a professional.",
      fact: "Up to 70%", factTitle: "of people who develop bunions have a family history.", factBody: "Reported by AAOS. This does not mean you have a 70% chance of developing a bunion.", source: "basics",
      steps: [["Know the background", "Mention your family history when discussing concerns with a foot specialist."], ["Choose space", "A roomy toe box is a concrete place to begin when reviewing your footwear."], ["Follow the evidence", "Look at study results and limitations when considering a new technology, including Albea."]],
      question: "Can Albea change my inherited risk?", answer: "That has not been established. The concept explores targeted muscle activation; it cannot promise that your family’s experience will not be repeated.",
      offer: "A considered approach for people thinking ahead.",
    },
    "active-living": {
      title: "For the life you love.", accent: "And the feet that take you there.",
      intro: "Walks, weekends outdoors, the next adventure. Your feet are part of every plan. Between activities, discover Albea: a muscle-focused concept designed for a quiet moment at home.",
      problemTitle: "Your next walk also deserves a moment of care.",
      problem: "A rubbing shoe or sensitive big toe can change how a day outdoors feels. Understanding persistent discomfort is more useful than simply ignoring it. Start with a closer look at your footwear and the changes you notice.",
      fact: "Every step", factTitle: "involves movement at the big-toe joint.", factBody: "As a bunion progresses, walking and finding comfortable shoes can become more difficult.", source: "basics",
      steps: [["Check the fit", "Look for toe room and notice where footwear rubs after an outing."], ["Listen to persistent pain", "Discomfort that changes your walking deserves assessment, not another performance promise."], ["Create a quiet moment", "Albea is conceived for use at rest. Session duration and settings remain to be validated."]],
      question: "Will Albea improve recovery or performance?", answer: "Those benefits are not established. Albea is not presented as a device to use while exercising. Safety, benefits and a use protocol still need to be studied.",
      offer: "A small ritual, between bigger adventures.",
    },
    "on-your-feet": {
      title: "You spend your day standing.", accent: "Make this moment yours.",
      intro: "Care work, retail, hospitality: your feet do a lot. Looking for less fatigue and more comfort? Start with what research says, then explore the Albea concept for time at home.",
      problemTitle: "Tired feet are not a failure of willpower.",
      problem: "Long periods in one standing position can take their toll. Work design and the opportunity to move matter. Albea is exploring a different moment: a simple muscle-focused routine while resting at home.",
      fact: "Movement matters", factTitle: "Long periods of standing are associated with fatigue.", factBody: "A NIOSH review identified physical fatigue and discomfort. Varying positions and moving were key recommendations.", source: "standing",
      steps: [["Change position", "Discuss opportunities to move, sit or lean during the workday."], ["Review the setup", "Footwear, flooring and work organization should be considered together."], ["Make space after work", "Albea’s open wrap concept brings four electrode positions into a proposed routine at rest."]],
      question: "Can Albea help me stand for longer?", answer: "That is not a demonstrated benefit. Workplace research does not validate Albea. The product cannot replace breaks, workplace adaptations or occupational health advice.",
      offer: "After caring for everything else. A moment for you.",
    },
    "lifelong-movement": {
      title: "Your walks. Your plans.", accent: "Your everyday freedom.",
      intro: "A trip to the market, a visit, a familiar walk. Comfortable feet matter to the small freedoms of everyday life. Explore practical foot-care habits and the Albea concept.",
      problemTitle: "Look after the feet that carry your day.",
      problem: "As the years pass, a tight shoe or a tender foot can take up more space in your day. A simple routine starts with noticing changes and discussing discomfort, rather than assuming pain is inevitable.",
      fact: "A daily check", factTitle: "is a practical foot-care habit.", factBody: "NHS foot-health advice includes checking your feet and choosing footwear with room for your toes and good support.", source: "feet",
      steps: [["Look regularly", "Notice your skin, pressure points and any changes in comfort."], ["Choose support", "Look for a secure fit, room for the toes and a shoe that supports your heel."], ["Start a conversation", "Difficulty walking deserves professional advice. A simple design does not establish suitability for everyone."]],
      question: "Is Albea suitable for every older adult?", answer: "Intended users and contraindications still need to be established. Conditions such as diabetes or altered sensation require individual advice. The concept does not promise fall prevention.",
      offer: "A little attention for the steps that matter.",
    },
  },
};
