import type { Locale } from "./content";
export type Source = { title: string; url: string };
export const sources: Record<Locale, Record<string, Source>> = {
  fr: {
    anatomy: { title: "Université de Tours · Anatomie de l’abducteur de l’hallux", url: "https://anthropotomia.univ-tours.fr/v2/glossaire/glossaire-les-muscles-liste.html" },
    muscleStudy: { title: "Ferrari & Vermand · Électrostimulation et posture (2016)", url: "https://www.em-consulte.com/article/1093816/effet-d-une-electrostimulation-du-muscle-abducteur" },
    basics: { title: "Assurance Maladie · Causes et évolution", url: "https://www.ameli.fr/assure/sante/themes/hallux-valgus/symptomes-causes-evolution" },
    care: { title: "Assurance Maladie · Les bons gestes", url: "https://www.ameli.fr/assure/sante/themes/hallux-valgus/bons-reflexes" },
    feet: { title: "Assurance Maladie · Prendre soin de ses pieds", url: "https://www.ameli.fr/assure/sante/bons-gestes/quotidien/prendre-soin-pieds" },
    standing: { title: "INRS · Station debout prolongée (2021)", url: "https://www.inrs.fr/dam/inrs/CataloguePapier/DMT/TI-QR-162.pdf" },
  },
  en: {
    anatomy: { title: "Glasoe · Muscle-strengthening rationale (2016)", url: "https://pubmed.ncbi.nlm.nih.gov/27266887/" },
    muscleStudy: { title: "Kim et al. · Toe-spread exercise trial (2015)", url: "https://pubmed.ncbi.nlm.nih.gov/25995546/" },
    basics: { title: "AAOS · Bunions", url: "https://www.orthoinfo.org/diseases--conditions/bunions/" },
    care: { title: "NHS · Bunions: care and prevention", url: "https://www.nhs.uk/conditions/bunions/" },
    feet: { title: "Guy’s and St Thomas’ NHS · Keeping feet healthy", url: "https://www.guysandstthomas.nhs.uk/health-information/falls/keeping-your-feet-healthy" },
    standing: { title: "CDC / NIOSH · Prolonged standing at work", url: "https://www.cdc.gov/niosh/bulletin/2014/standing.html" },
    trial: { title: "Moulodi et al. · Randomized trial (2025)", url: "https://pubmed.ncbi.nlm.nih.gov/38391279/" },
    exercise: { title: "Gateshead Health NHS · Exercises for bunions", url: "https://www.gatesheadhealth.nhs.uk/wp-content/uploads/2023/09/Patient-Information-on-Bunions.pdf" },
  },
};
export const education = {
  fr: {
    eyebrow: "COMPRENDRE L’HALLUX VALGUS",
    title: "Bien connaître ses pieds.", accent: "Pour mieux en prendre soin.",
    intro: "Pourquoi le gros orteil dévie-t-il ? Peut-on l’éviter ? Des repères concrets pour faire la part entre les gestes utiles, les traitements et les promesses.",
    facts: [
      { value: "≈ 30 %", title: "de la population âgée serait concernée", text: "Une estimation rapportée par l’Assurance Maladie, qui ne décrit pas le risque individuel.", source: "basics" },
      { value: "Plusieurs", title: "facteurs peuvent se combiner", text: "L’hérédité, l’âge et les chaussures étroites ou à talons font partie des facteurs favorisants.", source: "basics" },
      { value: "Pas toujours", title: "douloureux au début", text: "Une déviation peut exister sans douleur. Le confort ne renseigne pas à lui seul sur l’alignement.", source: "basics" },
    ],
    mechanismTitle: "L’« oignon » est une articulation qui se désaxe.",
    mechanismBody: "Le gros orteil se rapproche du deuxième, tandis que le premier métatarsien part dans l’autre sens. La saillie devient sensible aux frottements. Avec l’évolution, le chaussage et la marche peuvent devenir difficiles.",
    riskTitle: "Ce qui mérite votre attention",
    risks: [["La forme du pied", "Une prédisposition familiale peut compter. Cela ne permet pas de prédire votre évolution personnelle."], ["La pression dans la chaussure", "Un avant-pied comprimé et des talons hauts font partie des facteurs modifiables."], ["Une gêne qui évolue", "Frottements, inflammation et difficultés à marcher justifient de faire le point."]],
    preventionTitle: "Évitable à coup sûr ?", preventionAccent: "Non. Mais des gestes sont utiles.",
    preventionBody: "Les conseils de chaussage visent le confort et la limitation des contraintes. Ils ne constituent pas une garantie de prévention ni une correction de la déformation.",
    stimulationStepTitle: "Explorer l’électrostimulation",
    stimulationStepBody: "Solliciter les muscles du pied par des impulsions électriques est une piste à explorer en complément du renforcement, avec un professionnel. Pour albea Pulse, le gain de force et la prévention de l’hallux valgus restent à démontrer.",
    steps: [["Laisser de la place", "Choisissez des chaussures larges à l’avant, souples et sans couture qui frotte sur la zone sensible."], ["Réduire la pression", "Privilégiez des chaussures plates ou à petits talons et discutez des protections avec un professionnel."], ["Consulter au bon moment", "Une douleur importante, une gêne à la marche ou un oignon chaud, rouge et douloureux nécessitent un avis médical."]],
    distinctionTitle: "Soulager, corriger, prévenir : trois objectifs différents.",
    distinctions: [["Soulager", "Les soins, le chaussage et certains dispositifs peuvent aider les symptômes."], ["Corriger", "La chirurgie peut corriger la déformation lorsqu’elle est indiquée. Elle n’est pas systématique."], ["Prévenir", "Agir sur les contraintes ne supprime pas tous les facteurs de risque. Aucun résultat n’est garanti."]],
    evidenceTitle: "Pourquoi s’intéresser à ce muscle ?",
    muscleRoleTitle: "Un rôle dans le mouvement du gros orteil",
    muscleRole: "L’abducteur de l’hallux aide à écarter le gros orteil du deuxième et participe à sa flexion. Il relie le talon à la base du gros orteil, le long du bord interne du pied.",
    muscleRationaleTitle: "Le renforcer : dans quel but ?",
    muscleRationale: "L’idée est de travailler la capacité du pied à contrôler activement ce mouvement, opposé à la déviation du gros orteil vers les autres orteils. C’est un raisonnement biomécanique : renforcer ce muscle ne suffit pas, à lui seul, à garantir la prévention ou la correction d’un hallux valgus.",
    muscleStudyTitle: "Ce que la recherche explore",
    muscleStudy: "Une étude exploratoire sur 30 personnes a observé des changements du centre de pression pendant l’électrostimulation de ce muscle. Elle étudiait la posture, pas la prévention de l’hallux valgus ni un renforcement durable. Elle ne portait pas sur albea Pulse.",
    evidenceBody: "albea Pulse explore cette piste avec quatre électrodes : deux le long du muscle, une au-dessus et une en dessous du gros orteil. L’objectif de recherche est de solliciter ce muscle dans une routine simple à la maison.",
    evidenceNote: "À ce stade, Albea n’a pas démontré de prévention de l’hallux valgus, de correction, de réduction de la fatigue ou d’amélioration de l’endurance debout.",
    stimulationNote: "",
    sourceTitle: "Des sources à consulter, pas seulement à citer.",
  },
  en: {
    eyebrow: "UNDERSTANDING BUNIONS",
    title: "Know your feet.", accent: "Make informed choices.",
    intro: "Why does the big toe drift? Can a bunion be prevented? A clear guide to useful habits, treatment options and the limits of what we know.",
    facts: [
      { value: "Up to 70%", title: "have a family history", text: "Among people who develop bunions, according to AAOS. This is not your individual chance of developing one.", source: "basics" },
      { value: "Gradual", title: "changes in alignment", text: "Bunions often develop slowly as the position of the joint changes.", source: "basics" },
      { value: "More room", title: "is a practical starting point", text: "NHS guidance recommends correctly sized shoes with space for the toes.", source: "care" },
    ],
    mechanismTitle: "A bunion is a change in joint alignment.",
    mechanismBody: "The big toe angles toward the second toe while the first metatarsal shifts the other way. The prominent joint can rub against footwear. Changes can eventually affect comfort and walking.",
    riskTitle: "What deserves your attention",
    risks: [["Inherited foot structure", "Family history can contribute. It does not predict exactly what will happen to your feet."], ["Pressure from footwear", "Narrow toe boxes and poorly fitting shoes are factors you can address."], ["Changing comfort", "Irritation, swelling or difficulty walking are reasons to seek advice."]],
    preventionTitle: "Can you guarantee prevention?", preventionAccent: "No. Can you take useful steps? Yes.",
    preventionBody: "Roomier footwear can reduce pressure. Good habits do not guarantee that a bunion will never develop or reverse an existing deformity.",
    stimulationStepTitle: "Explore electrical stimulation",
    stimulationStepBody: "Activating foot muscles with electrical impulses is an approach to explore alongside strengthening, with a qualified professional. Strength gains and bunion prevention remain unproven for albea Pulse.",
    steps: [["Give your toes space", "Look for a wide toe box and a fit that does not squeeze or rub."], ["Reduce pressure", "Avoid high heels and pointed shoes. Discuss padding or inserts with a qualified professional."], ["Know when to ask", "Seek advice when pain persists, limits normal activities or the bunion gets worse. Foot problems with diabetes also need medical advice."]],
    distinctionTitle: "Relief, correction and prevention are different goals.",
    distinctions: [["Relief", "Footwear changes and other conservative measures can help discomfort."], ["Correction", "Surgery may be considered when symptoms persist despite nonsurgical care."], ["Prevention", "Addressing pressure cannot remove every risk factor. A guaranteed outcome is not established."]],
    evidenceTitle: "Why focus on this muscle?",
    muscleRoleTitle: "A role in big-toe movement",
    muscleRole: "The abductor hallucis helps move the big toe away from the second toe and contributes to flexion. It runs along the inside of the foot, from the heel to the base of the big toe.",
    muscleRationaleTitle: "What could strengthening it do?",
    muscleRationale: "The rationale is to train active control of a movement that opposes the big toe drifting toward the other toes. That makes it a useful target to investigate. Strengthening one muscle alone does not guarantee prevention or correction of a bunion.",
    muscleStudyTitle: "What exercise research suggests",
    muscleStudy: "In a small trial of 24 people with hallux valgus, eight weeks of toe-spread exercises plus an orthosis improved muscle cross-sectional area and toe angle compared with an orthosis alone. This was exercise research, not a test of electrical stimulation, albea Pulse or prevention.",
    evidenceBody: "albea Pulse explores this approach with four electrodes: two along the muscle, one above and one below the big toe. The research goal is to activate this muscle in a simple at-home routine.",
    evidenceNote: "Albea needs its own safety and efficacy studies. Prevention, correction, fatigue reduction and greater standing endurance have not been demonstrated for this product.",
    stimulationNote: "Exercise findings do not automatically transfer to stimulation. In a separate trial of 28 women, adding neuromuscular stimulation to orthoses and exercise provided no additional effect on the main outcomes after one month. That study did not test albea Pulse.",
    sourceTitle: "Read the evidence for yourself.",
  },
};
